name: kel7
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  pinch_zoom: ^1.0.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  get: ^4.6.5
  visibility_detector: ^0.3.3
  
  http: ^0.13.5 #http: ^1.1.0
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  open_filex: ^4.3.2
  # file_picker: ^5.3.2
  # image_picker: ^1.0.1
  currency_picker: ^2.0.16
  country_picker: ^2.0.20
  overlay_support: ^2.1.0
  flutter_easyloading: ^3.0.5
  flutter_phoenix: ^1.1.0
  flutter_image_compress: ^2.0.4
  mime_type: ^1.0.0
  pin_code_text_field: ^1.8.0
  lottie: ^2.3.2
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/lottie/
